<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DTW - Detroit Metropolitan Wayne County A_af51e6</name>
   <tag></tag>
   <elementGuidId>ee4fa00a-6daf-4243-bd54-8eefaa054828</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d02c8f0-40d0-49bb-9499-18766fd31ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-10</value>
      <webElementGuid>1bce0e25-1c2c-4d7a-87e6-4117c4414d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-corner-all ui-state-focus</value>
      <webElementGuid>3f54dfa9-0fee-4e06-8c3e-893b3b4e49e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b797d764-7273-413f-9003-93483bbe5fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DTW - Detroit Metropolitan Wayne County Airport, MI</value>
      <webElementGuid>15e68fdf-5d60-4763-8b6c-d2ae60e54a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-10&quot;)</value>
      <webElementGuid>bae9d476-d55d-45bb-bc04-372145317e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-10']</value>
      <webElementGuid>36f2938e-ac6e-42a7-b9bb-e590bc8d9162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[2]/a</value>
      <webElementGuid>54d8db51-b6e7-4ee8-a0e2-f4241318eefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DTW - Detroit Metropolitan Wayne County Airport, MI')]</value>
      <webElementGuid>c1a27854-fcfa-4f80-9d9c-fe754ebd550f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DTT - Detroit, MI'])[1]/following::a[1]</value>
      <webElementGuid>bb365c32-b4ec-4d36-9b80-88d97e0a48f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depart'])[1]/following::a[2]</value>
      <webElementGuid>b11aca21-09a9-4a4b-aea8-4ca0b25c625c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DTW - Detroit Metropolitan Wayne County Airport, MI'])[2]/preceding::a[1]</value>
      <webElementGuid>2e835ffc-96fd-43bb-8f16-5cd9a42ada85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close window'])[1]/preceding::a[1]</value>
      <webElementGuid>65bf0e1b-d662-476c-a98d-54bdb2c6348e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DTW - Detroit Metropolitan Wayne County Airport, MI']/parent::*</value>
      <webElementGuid>1b02de78-984b-435a-9a81-b67e5bfb098d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[2]/a</value>
      <webElementGuid>26d5bf8d-afd8-4036-97b4-8a5d89e910e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ui-id-10' and (text() = 'DTW - Detroit Metropolitan Wayne County Airport, MI' or . = 'DTW - Detroit Metropolitan Wayne County Airport, MI')]</value>
      <webElementGuid>5c92a66f-16e4-4e29-9e62-6447d7f3b31d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
