<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fare preference_flightSearchForm.butt_d1acf4</name>
   <tag></tag>
   <elementGuidId>102e99af-3b5d-4727-b921-3a2369272c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flightSearchForm.button.reSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca827425-f553-4ae3-87b0-38dbbd8d577d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>98cfdf5c-23b5-4883-a426-b7d22f01aca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>2296105c-eb00-4086-9a03-ee2be5b4ba46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flightSearchForm.button.reSubmit</value>
      <webElementGuid>10a9e5c8-e042-4dce-bae6-cc43430a7408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-fullWidth</value>
      <webElementGuid>eabc0218-af31-493f-a0cc-1a8d66d6c382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservationFlightSearchForm&quot;)/div[@class=&quot;row-form aa-flightSearchForm-datesRow&quot;]/div[@id=&quot;flightSearchFormSubmitButton&quot;]/div[1]/input[@id=&quot;flightSearchForm.button.reSubmit&quot;]</value>
      <webElementGuid>34248c5e-67ec-4d81-bc61-c0b3430a6765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flightSearchForm.button.reSubmit']</value>
      <webElementGuid>0ea37c9a-c501-44f6-a31a-b7d8a9fdae3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormSubmitButton']/div/input</value>
      <webElementGuid>f24c63c2-05b6-4ae3-aa4d-fe0e8037dd7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>5cbe4faf-353d-4df6-a3db-d3ff2b80d897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'flightSearchForm.button.reSubmit']</value>
      <webElementGuid>ef238fa6-7e55-4542-a883-e44dfe22eb9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
