<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(date format mmddyyyy)_returnDate</name>
   <tag></tag>
   <elementGuidId>83632666-2219-40e3-b950-601934c8f8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aa-returningFrom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aa-returningFrom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f8b9afb-cee7-4e99-934c-e5541bca3e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aaDatePicker hasDatepicker</value>
      <webElementGuid>c098b0b7-abb0-4c80-a63e-2a942778006a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aa-returningFrom</value>
      <webElementGuid>eddd0f57-433c-4a09-9e22-3ebae780fc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>returnDate</value>
      <webElementGuid>f2bef7a9-50b9-4e8d-b498-b7bb7c367001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>405aab2d-3e52-4c57-a49b-595f7619516d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>2d4a143e-185d-4d86-ac3d-72b899da6fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3bbfe25c-9c55-4e8a-8a86-3092e0b0b1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservationFlightSearchForm&quot;)/div[@class=&quot;row-form aa-flightSearchForm-datesRow&quot;]/div[@class=&quot;span4&quot;]/div[@class=&quot;js-date-picker-wrapper position-relative&quot;]/label[1]/input[@id=&quot;aa-returningFrom&quot;]</value>
      <webElementGuid>7247ace0-6749-49c1-83c1-884e43f805b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aa-returningFrom']</value>
      <webElementGuid>7d7d35a0-6ead-4595-95dd-a9d6293e408c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='reservationFlightSearchForm']/div[4]/div[2]/div/label/input</value>
      <webElementGuid>d1654b4a-8f0d-4f74-8cde-60596c680be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/label/input</value>
      <webElementGuid>1d9ace58-16ad-487a-98f3-2531147d3313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'aa-returningFrom' and @name = 'returnDate' and @type = 'text' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>c9e3bd16-23ba-44c8-a2e8-d6e5a2f02810</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
