<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_To_destinationAirport</name>
   <tag></tag>
   <elementGuidId>4a4e04b7-1892-4140-b532-933ba2e0ced8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reservationFlightSearchForm.destinationAirport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d13901a7-b528-4d97-828c-e0e62f567b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e93c7e7-d1b1-4b6b-82d2-e2bd6c6844e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destinationAirport</value>
      <webElementGuid>6b1bb152-1d82-4a22-9a09-d4ebb487d07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reservationFlightSearchForm.destinationAirport</value>
      <webElementGuid>1ba291d9-8109-4743-b52c-63a12ac04896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aaAutoComplete ui-autocomplete-input focus-visible</value>
      <webElementGuid>56cd2e6b-a570-4e9c-a80c-498f42262bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City or airport</value>
      <webElementGuid>b2c44253-b1ad-4d70-b550-48606d2a9501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3dc27ea1-15fa-4fc9-9473-224b3055659a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b8af7d18-2019-4946-b959-45ca9b576ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservationFlightSearchForm&quot;)/div[@class=&quot;row-form normalLayout&quot;]/div[@class=&quot;span4&quot;]/div[@class=&quot;position-relative margin-bottom&quot;]/label[1]/input[@id=&quot;reservationFlightSearchForm.destinationAirport&quot;]</value>
      <webElementGuid>a04f1b78-4914-453d-91b4-cdeaae7dcd0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reservationFlightSearchForm.destinationAirport']</value>
      <webElementGuid>b3a77d85-27dc-46f8-8092-15f1ac2936bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='reservationFlightSearchForm']/div[3]/div[2]/div/label/input</value>
      <webElementGuid>fed75ab0-fc69-40f6-99a8-aad184464959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>8392bc27-cac6-4c22-b0dc-7025fed27fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'destinationAirport' and @id = 'reservationFlightSearchForm.destinationAirport' and @placeholder = 'City or airport']</value>
      <webElementGuid>e49e8052-639f-481a-ab14-5b775b9e852d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
