<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From_originAirport</name>
   <tag></tag>
   <elementGuidId>3c3cc769-16a6-4074-a013-8899200cda5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reservationFlightSearchForm.originAirport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2333244e-8c72-46c6-b672-1275fd6c2236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4c89f35-ee61-4810-a530-a92003703cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>originAirport</value>
      <webElementGuid>99bfc3a7-884a-4f97-9a86-2c14e89d4c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DTT</value>
      <webElementGuid>c6c4e8b6-1c4d-46b6-b815-7baabf712d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reservationFlightSearchForm.originAirport</value>
      <webElementGuid>450b9d87-5658-4812-83ed-b5d981e3731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aaAutoComplete ui-autocomplete-input focus-visible</value>
      <webElementGuid>b5a7a448-2314-4592-9eba-4b7c1d906815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City or airport</value>
      <webElementGuid>fedb67c0-3560-4f36-aa06-cb148dcf57bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80fd58ef-c77f-48d0-b65b-b81a7ed86481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3c49f6c3-e6b4-401c-b098-106062a6c712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservationFlightSearchForm&quot;)/div[@class=&quot;row-form normalLayout&quot;]/div[@class=&quot;span4&quot;]/div[@class=&quot;position-relative margin-bottom&quot;]/label[1]/input[@id=&quot;reservationFlightSearchForm.originAirport&quot;]</value>
      <webElementGuid>d0fbafe7-738b-41f0-86cb-b9a3460d70eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reservationFlightSearchForm.originAirport']</value>
      <webElementGuid>12c086e1-4afa-4e4f-a853-2169bcc5bfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='reservationFlightSearchForm']/div[3]/div/div/label/input</value>
      <webElementGuid>64af3c91-f6ea-40ff-954d-a7f356f112d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>b6d588f8-f173-4200-8a65-b78347201b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'originAirport' and @id = 'reservationFlightSearchForm.originAirport' and @placeholder = 'City or airport']</value>
      <webElementGuid>850b4637-b5cf-46ec-87df-2267b681808d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
