<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(date format mmddyyyy)_departDate</name>
   <tag></tag>
   <elementGuidId>120bfdff-d3a5-43ad-9fa4-e21574bc273e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aa-leavingOn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aa-leavingOn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8cf933b-f948-4df1-855d-f974cb95c40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aaDatePicker hasDatepicker focus-visible</value>
      <webElementGuid>f4ae3f35-1261-4128-9ff4-b7d7e722f4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aa-leavingOn</value>
      <webElementGuid>cf08e986-383f-46ec-a642-5f6f3e9cff1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>departDate</value>
      <webElementGuid>8ba9f78a-9a54-4cc8-b67b-eaa141b7f588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15b65cd3-696e-413b-8728-42aabf8502d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>b2fd009a-c66d-48dd-b0c1-6b8fbf6d6776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9ce0e9a7-29d8-454f-92e9-322778a3b2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservationFlightSearchForm&quot;)/div[@class=&quot;row-form aa-flightSearchForm-datesRow&quot;]/div[@class=&quot;span4&quot;]/div[@class=&quot;js-date-picker-wrapper position-relative&quot;]/label[1]/input[@id=&quot;aa-leavingOn&quot;]</value>
      <webElementGuid>a01a2030-e637-4fd9-b6dd-b11a5eaf81de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aa-leavingOn']</value>
      <webElementGuid>3c8028d1-1706-4257-9835-3b4738ca6577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='reservationFlightSearchForm']/div[4]/div/div/label/input</value>
      <webElementGuid>5084802b-93b4-479e-be3d-8229bc075d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/label/input</value>
      <webElementGuid>92c83c6c-8d66-4bb2-8e45-34cc86070aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'aa-leavingOn' and @name = 'departDate' and @type = 'text' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>e18da953-0878-406b-a799-5676354f9e08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
