<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1                                   _5ab068</name>
   <tag></tag>
   <elementGuidId>e2423365-bcbe-45b1-9c66-b71dec78f7df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='flightSearchForm.adultOrSeniorPassengerCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>68b7652a-d405-45dc-8004-dd5c335dc29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adultOrSeniorPassengerCount</value>
      <webElementGuid>c7d93697-d425-41f6-b208-5449f431f1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>calcTotalNoOfPsgrsOnHomePage('')</value>
      <webElementGuid>87169238-8c7e-462a-9845-6131d87f7b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flightSearchForm.adultOrSeniorPassengerCount</value>
      <webElementGuid>d39241a8-1c21-4d61-9ef6-73e29e21cfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        1
                                        2
                                        3
                                        4
                                        5
                                        6
                                        7
                                        8
                                        9
                                    </value>
      <webElementGuid>6fcd2332-d53a-4f8c-a433-345bd641bfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reservationFlightSearchForm&quot;)/div[@class=&quot;row-form normalLayout&quot;]/div[@class=&quot;span4&quot;]/div[@class=&quot;margin-bottom&quot;]/label[1]/select[@id=&quot;flightSearchForm.adultOrSeniorPassengerCount&quot;]</value>
      <webElementGuid>00a9331d-b0cf-4401-8945-91cb03fd8567</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='flightSearchForm.adultOrSeniorPassengerCount']</value>
      <webElementGuid>9790f872-0e96-436e-910d-751493a683c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='reservationFlightSearchForm']/div[3]/div[3]/div/label/select</value>
      <webElementGuid>68dbb4f4-aa5e-4522-b997-51ca559ec5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To airport look up'])[1]/following::select[1]</value>
      <webElementGuid>aa94f726-5683-4f5d-9fb8-1992472a0b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(date format mm/dd/yyyy)'])[1]/preceding::select[1]</value>
      <webElementGuid>1404a729-4b0d-4f80-8135-4b2faa194ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b7f22786-82cf-4c5b-a5c7-369ef40dbb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'adultOrSeniorPassengerCount' and @id = 'flightSearchForm.adultOrSeniorPassengerCount' and (text() = '
                                        1
                                        2
                                        3
                                        4
                                        5
                                        6
                                        7
                                        8
                                        9
                                    ' or . = '
                                        1
                                        2
                                        3
                                        4
                                        5
                                        6
                                        7
                                        8
                                        9
                                    ')]</value>
      <webElementGuid>ceb6b4fb-48f7-44f8-b026-5321aa0edc2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
